### ISSUE TITLE
Database options

### ISSUE THREAD

**Issue by Gerv-G** [ProgrammingPhilippines/progphil-bot#11]
### **As an** 
Development Team

### **I want to** 
Discover whether we need a database to be implemented for the PPH Bot

### **In order to** 
Be able to implement features that will require saving data in a database

***

### Acceptance Criteria
- [x] Discuss and answer the following questions
   - Do we need a database?
   - What database are we going to use?
   - Where and how are we going to host it?
   - Costing
- [ ] Documentation on the findings available in the Wiki

**Comment by jovelluna12** [comment]
> Do we need a database?

If feature request #17 gets approved, yes we will .  The question is, what database will we use? Is MySQL even a Good Choice?

**Comment by Jedddy** [comment]
Postgres ftw

**Comment by ssuish** [comment]
just postgres
