### ISSUE TITLE
[PROD] Dev-Help Auto Tag not working

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#111]
**Describe the bug**
Auto mention of Dev-Help Volunteer role is no longer working in Prod

**To Reproduce**
1. Create a new post in dev-help

**Expected behavior**
1. PPH bot auto mentions specified roles

**Screenshots**
![image](https://user-images.githubusercontent.com/11833469/227754378-9d569ab9-7d9d-4c8a-8759-77938d0c223c.png)

![image](https://user-images.githubusercontent.com/11833469/227754387-b9466769-81e4-4728-ac1e-17ad1a000cbb.png)

**Comment by vouchard** [comment]
### Caused by:
- renamed DB column.

### corrective actions
Rename db column to original name

> no changes on production codebase and funtionalities
