### ISSUE TITLE
Access the "define" feature via prefix

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#127]
### **As a** 
User

### **I want to** 
Use the `/define` command via prefix

### **In order to** 
Interact with the `define` feature without using slash commands

***

### Acceptance Criteria
- [x] The `define` word feature must be triggerable with a prefix-based execution
- [x] Use `pph-define` to trigger
- [x] Format should be `pph-define <word>`

**Comment by vouchard** [comment]
tested using
pph-define "no input"
pph-define  123
pph-define !@#@$%
pph-define 2011-01-01

all GOOD, LGTM,
waiting for other QA, )

**Comment by allendlr** [comment]
LGTM!
