### ISSUE TITLE
Initial Code Base

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#21]
### **As a** 
Developer

### **I want to** 
Initialize the code base for the project

### **In order to** 
Kickstart the development of the project with a base code structure and directories

***

### Acceptance Criteria

- [x] Base classes/code must be visible in the codebase
- [x] Directories must be well-defined for source codes, configurations, resources, etc
- [x] Codebase must be available in the **main** branch

**Comment by Jedddy** [comment]
*Finished all these*
