### ISSUE TITLE
Command for creating single-line announcements

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#26]
### **As a** 
Developer

### **I want to** 
Use a chat command

### **In order to** 
Instruct the bot to create a single-line announcement in any target channel

***

### Acceptance Criteria

- [x] Single-line announcements can be triggered via chat command 
- [x] Chat command can be made from any channel
- [x] Chat command can only be triggered by specific roles or users
- [x] Announcements must be single-line only
- [x] Announcements must be visible only to the target channel only
- [x] Announcements must be able to use Discord markdowns
- [x] Produce a specifications document on how to use the command

**Comment by jovelluna12** [comment]
command syntax would be /announce <the_announcement_message_here>

**Comment by jovelluna12** [comment]
- Announce Command
    - Arguments
        - announce
            - A single-line message that is to be announced

example
/announce this is an announcement
