### ISSUE TITLE
Add a config file, and a loader

### ISSUE THREAD

**Issue by Jedddy** [ProgrammingPhilippines/progphil-bot#36]
### **As** 
Developer(s), Lead

### **I want to** 
Add a config file, and a loader file that loads configuration into python objects.

### **In order to** 
Make it easier for developers to use the right configurations without populating the file they're working on with configs
***

### Acceptance Criteria

- [ ] Loads config to dataclasses
- [ ] No issues
- [ ] Tested multiple times

**Comment by CunningBard** [comment]
guys dont forget to close your Issues
