### ISSUE TITLE
Add Error Handling

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#49]
### **As** 
Developer(s), UX

### **I want to** 
Add an error-handling to the bot

### **In order to** 
Provide a better user experience by informing bot users of errors or mistake committed when executing commands.

***

### Acceptance Criteria

- [x] Bot will respond with an error message, visible only to the specific user, whenever he/she commits a mistake when executing a bot command
- [x] The command must not push through if an error is committed

### Example
![Image](https://user-images.githubusercontent.com/11833469/212708197-b49911d5-3f32-44d4-99f2-177d92c11e40.png)

**Comment by tora-o** [comment]
created a PR for this #54
