### ISSUE TITLE
Allow mentioning roles and users in announcement

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#50]
### **As an** 
Developer(s)

### **I want to** 
Allow mentioning of roles, and/or users when creating an announcement

### **In order to** 
Send notifications/alerts to all concerned roles/users regarding a certain announcement

***

### Acceptance Criteria

- [x] User must be able to **optionally** select multiple roles or users when creating an announcement
- [x] The announcement must _ping_ all mentioned roles/users when the announcement is posted
- [x] The bot should be able to handle mentions in multi-line/multi-media announcements

**Comment by CunningBard** [comment]
fun, lemme help doing this
