### ISSUE TITLE
Wont stop processing after an announcement made with /announce command

### ISSUE THREAD

**Issue by E-V-Castillo** [ProgrammingPhilippines/progphil-bot#55]
**Describe the bug**
After issuing the announce command without a photo, the form pops up and takes in its values, when submitted, the processing does not stop. It has gone on for 10 minutes already.

**To Reproduce**
1. Use announce without a photo

**Expected behavior**
Expected an announcement to be made with a title and the actual announcement

**Screenshots**
![image](https://user-images.githubusercontent.com/116155431/212856048-3048cbe0-d594-482f-8859-7715c29747d5.png)

**Desktop (please complete the following information):**
Linux-Ubuntu-22.04

**Comment by jovelluna12** [comment]
yeh encountered this bug as well. haven't tested it but one way of fixing it is by replying with interaction reply function. so far, all messages were sent using channel .send , we could fix this bug by setting the reply to ephemeral=true and set the message to like "announcement has been made" , or something like that.

**Comment by Jedddy** [comment]
This is a bug from the discord API itself
