### ISSUE TITLE
Dynamic Badges

### ISSUE THREAD

**Issue by Gerv-G** [ProgrammingPhilippines/progphil-bot#8]
**Problem/Motivation**
- Badges to show build status and other pertinent information about the project
- Badges should update on every merge to `main` branch

**Proposed Solution**
A good option might be the [Dynamic Badge Action](https://github.com/marketplace/actions/dynamic-badges) available in the GitHub marketplace.

### Acceptance Criteria

- [x] Dynamic badges are present in the repository (Probably in README.md, etc)
- [x] CI Status, licensing info, tools used, frameworks, languages, etc

**Comment by jovelluna12** [comment]
made a PR for this. #52
