### ISSUE TITLE
Unknown Errors log into a specific channel

### ISSUE THREAD

**Issue by CunningBard** [ProgrammingPhilippines/progphil-bot#83]
I'm always frustrated when we only find out a bug if we ssh into a server and check into the docker logs

What I'm thinking is that on [line](https://github.com/ProgrammingPhilippines/progphil-bot/blob/118942afc81838af74e856e4b68e15a7978eb6af/bot/cogs/error_handling.py#L39) instead of using the `get` method, we instead do a normal conditional, and if it doesn't exist we log the error and return the message

This is very helpful for finding out that an error occurred since I'm thinking of pinging the devs when an unknown error happens

**Comment by CunningBard** [comment]
```py
error_message = None
if type(error) not in error_map:
    bot_err_log.send_message(f"Error: '{error}' has occured")
    error_message = self.error_message
else:
    error_message = error_map[(type(error)]
    
error_message = error_message.format(error=error)  # formats the error message if it has a format string
```

**Comment by kylecdrck** [comment]
Prod Server Channel for logs; #system-logs
