### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Gerv-G** [ProgrammingPhilippines/progphil-bot#9]
**Problem/Motivation**
> 🚫 **Blocked** - project is still in revival phased and doesn't have enough functionality yet worthy to be described in the README

As of writing, our readme doesn't contain enough information to tell what the project is all about and how one can contribute to it.
One good inspiration is [this template](https://github.com/othneildrew/Best-README-Template)

### **As a** 
Developer, Lead

### **I want to** 
Improve the README file

### **In order to** 
Have a developer documentation readme for the discord bot repository

***

### Acceptance Criteria

- [ ] README.md must be included in the **main** branch
- [ ] Must contain all necessary information regarding the project
- [ ] Must have a brief instructions on how to clone and start working on the project
- [ ] Include necessary links to project files, wiki pages, and/or documentations if necessary

**Comment by jovelluna12** [comment]
@Jedddy pls check template attached by sir gerv for readme
