### ISSUE TITLE
Improvements on Announcements

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#98]
### **As a** 
Admin, and User

### **I want to** 
Have improvements on the existing Announcement features

### **In order to** 
Enhance the user experience when interacting with the said features

***

### Acceptance Criteria
- [x] #99
- [ ] Unify **mention** and **add media** in the /announce command. When using /announce, the modal should already provide features for inserting media and mentioning roles/users/channels by default since /announce without using any of the two features is just /shout
- [ ] Add a feature to specifically mention roles/users/channels in a user-defined order instead of in a predefined order _(fig 2)_. Maybe indexing like $user0 -> $userN, $role0 -> $roleN can be used instead to allow personalization of messages based on mention tags

### Nice to have
- [x] Maybe add an option to submit the announcement either as an Embed or as a regular post
- [ ] Show the selection of mentions first before the dialog

***

Fig 1:

![Image](https://user-images.githubusercontent.com/11833469/224486712-235521fe-5b8c-49ed-adf7-bda1be33def1.png)

![Image](https://user-images.githubusercontent.com/11833469/224487061-8c5b1886-b4a3-4a40-a44c-b8a341e156a6.png)

Fig 2:

![Image](https://user-images.githubusercontent.com/11833469/224486797-579701d1-872c-4c9e-94a2-1be447d2989f.png)

![Image](https://user-images.githubusercontent.com/11833469/224486805-6377801b-5d7d-49d5-a176-fcb878b623b7.png)

![Image](https://user-images.githubusercontent.com/11833469/224486821-7c75c8b1-1e0b-4e9c-ade0-db4e7e2a14e2.png)

**Comment by Jedddy** [comment]
> Add a feature to specifically mention roles/users/channels in a user-defined order instead of in a predefined order (fig 2). Maybe indexing like $user0 -> $userN, $role0 -> $roleN can be used instead to allow personalization of messages based on mention tags

wait isnt this the same as right now? kase sunod sunod pa den? or should it work like $user1, $user0, $user4, $user3

**Comment by Jedddy** [comment]
> Unify mention and add media in the /announce command. When using /announce, the modal should already provide features for inserting media and mentioning roles/users/channels by default since /announce without using any of the two features is just /shout

make media a required parameter?

**Comment by CunningBard** [comment]
> > Add a feature to specifically mention roles/users/channels in a user-defined order instead of in a predefined order (fig 2). Maybe indexing like $user0 -> $userN, $role0 -> $roleN can be used instead to allow personalization of messages based on mention tags
> 
> wait isnt this the same as right now? kase sunod sunod pa den? or should it work like $user1, $user0, $user4, $user3

what if its 
"""
To $user0, $user0 has been the greatest dev in the company, along with $user1, $user0 has been doing his best in making this project to work, $user0 also...
"""

**Comment by Jedddy** [comment]
> > > Add a feature to specifically mention roles/users/channels in a user-defined order instead of in a predefined order (fig 2). Maybe indexing like $user0 -> $userN, $role0 -> $roleN can be used instead to allow personalization of messages based on mention tags
> > 
> > 
> > wait isnt this the same as right now? kase sunod sunod pa den? or should it work like $user1, $user0, $user4, $user3
> 
> what if its
> 
> > To $user0, $user0 has been the greatest dev in the company, along with $user1, $user0 has been doing his best in making this project to work, $user0 also...

i tried doing that, unfortunately its impossible since the items returned from the selection gets sorted by their id 😢

**Comment by Jedddy** [comment]
>  Unify mention and add media in the /announce command. When using /announce, the modal should already provide features for inserting media and mentioning roles/users/channels by default since /announce without using any of the two features is just /shout

if i understand this right, this is impossible *for now* since modals only support text inputs

**Comment by allendlr** [comment]
no major issues :)
